### PR TITLE
feat: add macOS platform support

### PR DESCRIPTION
**Pull request by mxknt**
## Description

This PR adds macOS as a supported platform, including the required XCode build configurations and run schemes to support the usual three Flutter flavors: `production`, `staging` and `development`. See VeryGoodOpenSource/very_good_cli#452

The process of adding macOS support took the following steps (roughly mapped to the included commits):
- add the basic macOS project scaffold using `flutter create --platforms=macos .`, removing the new `main.dart` and other unneeded files that the command added.
- add the required xcode build configurations for each flavor, `Debug-development`,  `Release-staging` etc.
- update the bundle id for the development and staging build configurations, adding a `.dev` and `.stg` suffix respectively.
- add icon assets for each flavor
- add xcode run schemes for each flavor

## Type of Change

- [x] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [x] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Comment by mxknt** [comment]
Let me now if I should run the generator and commit the changes to the brick here, or if that should happen separately.

**Comment by renancaraujo** [comment]
> Let me now if I should run the generator and commit the changes to the brick here, or if that should happen separately.

It is okay, it will run automatically after merge

**Review by renancaraujo — APPROVED** [review]

**Comment by renancaraujo** [comment]
Thanks for your contribution!

**Comment by parsa10** [comment]
Has this been activated? I'm not receiving the macOS configuration even after executing the 'very_good create' command.

> Thanks for your contribution!

**Comment by alestiago** [comment]
@parsa10 this has mot been published yet. We'll most likely publish next week, after that you'll see the changes.

If you want to get notified upon release you can use GitHub to Watch for releases 🙌

**Comment by alestiago** [comment]
#314 is tracking the release of this feature.

**Pull request merged**
