### PR TITLE
test: included golden e2e test

### LINKED ISSUE #220: fix: add e2e tests for very_good_core
As a developer, I want to have e2e tests running in the CI as part of very_good_core to ensure the brick is always functioning as expected (similar to e2e tests in very_good_cli).

### PR DESCRIPTION
**Pull request by alestiago**
## Description

Adds a test that compares the generated files against a pre-generated fixture.

This PR is a follow-up of #245 to resolve #220.

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore
- [X] 🧪 Tes

### CODE REVIEW

**Comment by renancaraujo** [comment]
I am curious to know the workflow for future contributions on templates:
- Open pr with changes
- After merge, merge a pr with changes in the brick (generated automatically)
- Open pr to update the fixture

This will mean that the build will be broken between steps 2 and 3. Also will mean that each change in the template will need 3 prs 2 of them manually opened.

**Comment by alestiago** [comment]
@renancaraujo I think the workflow is as follows:

1. Open a PR.
2. If your PR changes the generated output then in the same PR update the fixtures (similar to how you would do `flutter test --update-goldens`). If the PR doesn't change the fixtures then there is no need to update them.

**Comment by renancaraujo** [comment]
> @renancaraujo I think the workflow is as follows:
> 
> 1. Open a PR.
> 2. If your PR changes the generated output then, in the same PR, update the fixtures (similar to how you would do `flutter test --update-goldens`). If the PR doesn't change the output then there is no need to update them.
> 
> Let me know if you're thinking of any amendments here.



Then we need to update the workflow that generates the second pr

**Review by wolfenrain — APPROVED** [review]

**Review by wolfenrain — APPROVED** [review]

**Comment by renancaraujo** [comment]
We decided to no go forward with fixture tests for the resulting application dut to some concerns:

> Today the template bricks are generated by [a workflow](https://github.com/VeryGoodOpenSource/very_good_core/blob/main/.github/workflows/generate_very_good_core.yaml). This is done to guarantee that the brick always looks the same regardless of local configs and to keep PRs updating the template code small. Adding the fixture test means we must remove that workflow and always generate the bricks locally. This means that any update on the template would have PRs with every change in 3 different places, the template, the brick, and the fixture.
Also, moving the brick generation to local brings lots of variables into question, like local configs, the version of flutter/dart people have in their pcs when generating, etc etc

**Pull request closed without merging**
